-- =============================================================================
-- 20260826000000_final_production_parity.sql
-- FINAL production-parity reconciliation migration.
-- Evidence: live read-only catalog queries against production 2026-08-25.
-- All 5 divergent tables confirmed 0 rows via COUNT(*) on production.
-- =============================================================================

-- =============================================================================
-- P0: TABLE GRANTS -- restore DML privileges for PostgREST access
-- =============================================================================
DO $grants$
DECLARE r record;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tableowner='postgres' ORDER BY tablename
  LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO anon, authenticated, service_role', r.tablename);
  END LOOP;
END$grants$;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO anon, authenticated, service_role;

-- =============================================================================
-- P1: FOREIGN KEYs -- profiles(id) ON DELETE CASCADE per production
-- =============================================================================

-- chat_messages.user_id
ALTER TABLE public.chat_messages DROP CONSTRAINT IF EXISTS chat_messages_user_id_fkey;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- notes.user_id
ALTER TABLE public.notes DROP CONSTRAINT IF EXISTS notes_user_id_fkey;
ALTER TABLE public.notes ADD CONSTRAINT notes_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- transcripts.user_id
ALTER TABLE public.transcripts DROP CONSTRAINT IF EXISTS transcripts_user_id_fkey;
ALTER TABLE public.transcripts ADD CONSTRAINT transcripts_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- payments.user_id
ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_user_id_fkey;
ALTER TABLE public.payments ADD CONSTRAINT payments_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- analytics_events: production has NO user_id. Drop FK + column.
ALTER TABLE public.analytics_events DROP CONSTRAINT IF EXISTS analytics_events_user_id_fkey;
ALTER TABLE public.analytics_events DROP COLUMN IF EXISTS user_id;

-- =============================================================================
-- P3: analytics_events -- align to production (int serial id, event_type, metadata)
-- =============================================================================
DROP TABLE IF EXISTS public.analytics_events CASCADE;

CREATE TABLE public.analytics_events (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type  text,
  metadata    jsonb,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.analytics_events TO anon, authenticated, service_role;

DROP POLICY IF EXISTS analytics_events_insert_authenticated ON public.analytics_events;
DROP POLICY IF EXISTS analytics_events_select_none ON public.analytics_events;
DROP POLICY IF EXISTS analytics_events_delete_none ON public.analytics_events;
DROP POLICY IF EXISTS analytics_events_update_none ON public.analytics_events;

CREATE POLICY analytics_events_insert_authenticated ON public.analytics_events
  FOR INSERT WITH CHECK ((SELECT auth.uid() AS uid) IS NOT NULL);
CREATE POLICY analytics_events_select_none ON public.analytics_events
  FOR SELECT USING (false);
CREATE POLICY analytics_events_delete_none ON public.analytics_events
  FOR DELETE USING (false);
CREATE POLICY analytics_events_update_none ON public.analytics_events
  FOR UPDATE USING (false) WITH CHECK (false);

-- =============================================================================
-- P3: chat_messages -- align to production (messages jsonb)
-- =============================================================================
DROP TABLE IF EXISTS public.chat_messages CASCADE;

CREATE TABLE public.chat_messages (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id  uuid NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  messages    jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chat_messages TO anon, authenticated, service_role;

CREATE POLICY chat_messages_select_for_user ON public.chat_messages
  FOR SELECT USING (user_id = (SELECT auth.uid() AS uid));
CREATE POLICY chat_messages_insert_for_user ON public.chat_messages
  FOR INSERT WITH CHECK (user_id = (SELECT auth.uid() AS uid));

CREATE INDEX IF NOT EXISTS idx_chat_messages_meeting_id ON public.chat_messages(meeting_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON public.chat_messages(user_id);

-- =============================================================================
-- P3: notes -- add position CHECK, set columns NOT NULL per production
-- =============================================================================
ALTER TABLE public.notes
  ALTER COLUMN content SET NOT NULL,
  ALTER COLUMN content SET DEFAULT ''::text,
  ALTER COLUMN user_id SET NOT NULL,
  ALTER COLUMN meeting_id SET NOT NULL;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='notes_position_check' AND conrelid='public.notes'::regclass) THEN
    ALTER TABLE public.notes ADD CONSTRAINT notes_position_check CHECK (position >= 0);
  END IF;
END$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.notes TO anon, authenticated, service_role;

-- =============================================================================
-- P3: payments -- align to production (ZAR columns)
-- =============================================================================
DROP TABLE IF EXISTS public.payments CASCADE;

CREATE TABLE public.payments (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan_tier             text NOT NULL,
  billing_cycle         text NOT NULL,
  amount_zar            numeric(10,2) NOT NULL,
  currency              text DEFAULT 'ZAR',
  status                text DEFAULT 'completed',
  peach_transaction_id  text,
  amount                int,
  created_at            timestamptz DEFAULT now()
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payments TO anon, authenticated, service_role;

CREATE POLICY payments_select_for_user ON public.payments
  FOR SELECT USING (user_id = (SELECT auth.uid() AS uid));
CREATE POLICY payments_insert_for_user ON public.payments
  FOR INSERT WITH CHECK (user_id = (SELECT auth.uid() AS uid));

CREATE INDEX IF NOT EXISTS idx_payments_user_id ON public.payments(user_id);

-- =============================================================================
-- P3: transcripts -- align to production (entries jsonb)
-- =============================================================================
DROP TABLE IF EXISTS public.transcripts CASCADE;

CREATE TABLE public.transcripts (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id  uuid NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  entries     jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE public.transcripts ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.transcripts TO anon, authenticated, service_role;

CREATE POLICY transcripts_select_for_user ON public.transcripts
  FOR SELECT USING (user_id = (SELECT auth.uid() AS uid));
CREATE POLICY transcripts_insert_for_user ON public.transcripts
  FOR INSERT WITH CHECK (user_id = (SELECT auth.uid() AS uid));

CREATE INDEX IF NOT EXISTS idx_transcripts_meeting ON public.transcripts(meeting_id);

-- =============================================================================
-- P2: EXTENSIONS -- pg_net for catalog parity
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS pg_net;

-- =============================================================================
-- VERIFICATION: ensure all public tables have DML grants
-- =============================================================================
DO $verify_grants$
DECLARE r record;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tableowner='postgres' ORDER BY tablename
  LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO anon, authenticated, service_role', r.tablename);
  END LOOP;
END$verify_grants$;

-- =============================================================================
-- END OF 20260826000000_final_production_parity.sql
-- =============================================================================

-- =============================================================================
-- P1 fix: subscription_webhook_events.created_at (production has it, local missing)
-- =============================================================================
ALTER TABLE public.subscription_webhook_events ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
